### ISSUE TITLE
Missing WORKSPACE file in release 1.0.0 up to 1.0.2 tar.gz files

### ISSUE THREAD

**Issue by BrunoChevalier** [bazelbuild/bazel-skylib#210]
Is there a reason that the WORKSPACE file isn't present in the tar.gz files of the 1.0.0 release up to 1.0.2 release?
[bazel-skylib-1.0.2.tar.gz](https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.2/bazel-skylib-1.0.2.tar.gz) -> no WORKSPACE
[bazel-skylib-1.0.1.tar.gz](https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.1/bazel-skylib-1.0.1.tar.gz) -> no WORKSPACE
[bazel-skylib-1.0.0.tar.gz](https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.0/bazel-skylib-1.0.0.tar.gz) -> no WORKSPACE
[bazel_skylib-0.9.0.tar.gz](https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz) -> WORKSPACE

**Comment by c-parsons** [comment]
Confirmed. Paging aiuto@

**Comment by aiuto** [comment]
This is by design. *Users* of skylib do not require the WORKSPACE file. If you want to modify and enhance syklib, then you should clone it rather than get the distribution. We've been trying to divide packaging so that users of a repo do not have to depend on all the tools which might be needed to build and package that repo for reuse. For example, many repositories depend on stardoc to create doc files. A user of a repository which does so should not have to depend on stardoc if they do not use it themselves.

**Comment by BrunoChevalier** [comment]
Ok, thanks for the clarification
