### ISSUE TITLE
master.zip unavailable?

### ISSUE THREAD

**Issue by julovi** [bazelbuild/bazel-skylib#293]
Hi,

I'm very new to bazel and I'm sorry for maybe asking something obvious. I'm trying to install eidos (https://github.com/google/eidos-audition), but when I run ` bazel build -c opt ...` I get the following error:

Error downloading [https://github.com/bazelbuild/bazel-skylib/archive/master.zip] 

I checked and the "archive" directory doesn't exist, am I missing something?

Thanks for your help!

**Comment by tetromino** [comment]
Hi, I do apologize for the breakage. We thought that renaming the default branch from master to main (see https://github.com/bazelbuild/bazel-skylib/issues/281) would be painless, but it turns out that it broke a few projects which were using bazel-skylib from git master branch head instead of referring to a specific release (e.g. version 1.0.3).

I've proposed a PR for to fix eidos-audition: https://github.com/google/eidos-audition/pull/2 - hopefully the maintainers will merge it soon.

**Comment by aiuto** [comment]
IMO, no one should ever use 'master.zip' from a project that does numbered releases. What that means is, "Give me whatever you have today, without any promise that it works."
- The first choice should be a versioned, released artifact.
- The second should be a fetch at a specific tag or commit.
- The third should be to clone the repo.
