### ISSUE TITLE
Feature request: a function that helps propagate implicitly added attributes

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel-skylib#51]
When a rule is wrapped in a macro or a rule instantiates another rule is it often needed to propagate implicitly added attributes like tags and visibility. Maybe there should be some helper function for this in skylib?

See https://github.com/bazelbuild/rules_k8s/pull/137, the issue it fixes https://github.com/bazelbuild/rules_k8s/issues/123 and a similar issue in rules_docker https://github.com/bazelbuild/rules_docker/issues/269.
I guess many rules suffer from the same issue - implicit attributes are not propagated. Documenting what is the right thing to do in the "how to write rules" document (https://docs.bazel.build/versions/master/skylark/rules.html) would be great.

**Comment by brandjon** [comment]
IIUC the issue is about making it easy for a macro to instantiate rules using the same values for built-in attrs as are passed to the macro itself.

I don't think this problem is specific to built-in attrs. Even for explicitly defined attributes like "srcs", you still have to pass it to the macro and the macro has to propagate it to the relevant targets. Alternatively, you can use **kargs, which shouldn't distinguish between names of built-in attrs versus other kinds of args.

It's also not clear that it's generally intended/correct to use the same built-in attr values for all targets generated by a macro. Maybe one of them is "internal" and shouldn't have public visibility, even if another target is public.

**Comment by ash2k** [comment]
Ok, fair enough. Thank you.
